version: 2.1

orbs:
  node: circleci/node@4.1.0
  # for posting a GitHub PR comment
  pr-commenter: circleci/github-pull-request@0.2.0

jobs:
  test:
    executor:
      name: node/defaulta
      tag: "22.15.1"         
    steps:
      - checkout
      # runs `npm ci` by default with caching
      - node/install-packages
      - run:
          name: Run tests
          command: npm test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: reports
      - pr-commenter/comment:
          github-token: $GITHUB_TOKEN
          body: |
            #### :white_check_mark: Test Summary
            $(circleci tests summary)

workflows:
  test-and-comment:
    jobs:
      - test
