version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  test:
    executor:
      name: node/default
      tag: "22.15.1"
    steps:
      - checkout
      - run: npm install
      - run: mkdir ~/junit
      - run:
          command: npm test
          environment:
            MOCHA_FILE: ~/junit/test-results.xml
          when: always
      - store_test_results:
          path: ~/junit

workflows:
  test-and-comment:
    jobs:
      - test
