version: 2.1

orbs:
  node: circleci/node@4.1.0
  # for posting a GitHub PR comment
jobs:
  test:
    executor:
      name: node/defaulta
      tag: "22.15.1"         
    steps:
      - checkout
      # runs `npm ci` by default with caching
      - node/install-packages
      - run:
          name: Run tests
          command: npm test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: reports

workflows:
  test-and-comment:
    jobs:
      - test
